### ISSUE TITLE
Holding button fails to turn strip off

### ISSUE THREAD

**Issue by danhartline** [julianh2o/ESPLEDControl#4]
The "couch" strip did not turn off by holding the button down for 10 sec. (the tree strip did in ~3 sec).  Exiting the program did not help.

**Comment by julianh2o** [comment]
Try resetting the strip by unplugging it and plugging it back in. Then hold the button to turn it off.

**Comment by danhartline** [comment]
Tried that -- now the strip won't turn on at all, whether I hold the button before pluggig in or wait until after.

**Comment by julianh2o** [comment]
The one on the sofa is the newest version of the firmware. You will NEVER have to hold the button down on that one as you plug it in. Instead reset it by unplugging it and replugging it. Then, once the unit is on, tap the button once.

**Comment by julianh2o** [comment]
This seems to have been a hardware issue with your particular Flickerstrip.. I added a hack to fix yours and I'll monitor future units.

**Comment by danhartline** [comment]
It has been working like a charm at Laukahi (of course, I have left it
plugged in). There was some initial "settling in" when I first set it up
and was getting the wifi properly initialized, but no problems since (I
turn it on every evening when it gets dark - have some ideas on new
patterns but haven't had time to implement them yet).  When I had to turn
off the wifi for a bit to fix a faulty connection the Flickerstrip showed
up as a separate "router" on the wifi menu (I guess when the router
disappeared for a bit, it reverted to its own channel?), but it "cured"
itself and the software has been working on the regular router channel
again (I'm not sure how do describe it accurately -- I take it the
Flickerstrip changes its wifi channel somehow to listen to the one the
computer is communicating with rather than its default channel?). I
installed the 3D-printed case -- perfect fit.  The circuit board is
protected now.  Pua loves the strip -- you could market it as parrot
entertainment :-).

D

BTW, I read up a little on wifi channels -- it sounds as if I should try
to set the wifi to channels 1, 6 or 11 to get top speed (haven't figured
out how to do that yet :-).  Will that screw up Flickerstrip (or for that
matter the Laukahi printer)?

> This seems to have been a hardware issue with your particular
> Flickerstrip.. I added a hack to fix yours and I'll monitor future units.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Flickerstrip/FlickerstripApp/issues/4#issuecomment-180109656

## 

Daniel K. Hartline
Research Professor and Director
Bekesy Laboratory of Neurobiology
Pacific Biosciences Research Center
University of Hawaii at Manoa
Honolulu, HI 96822
www.pbrc.hawaii.edu/~danh

**Comment by julianh2o** [comment]
Changing the WiFi channel shouldn't affect Flickerstrip's connectivity.
Glad to hear everything is working well now!
