### ISSUE TITLE
Hot power unit

### ISSUE THREAD

**Issue by danhartline** [julianh2o/ESPLEDControl#5]
The power unit on the sofa strip was very hot after just half an hour of operation (setting was 97% power).  I think it is being run at too high an intensity.  In contrast, the tree unit doesn't even feel warm.  Do these units have thermal safety-cutoffs (I would judge that this one does not)?  For an item of consumer electronics where a fire could be disastrous to your firm, that might be a good idea.

**Comment by julianh2o** [comment]
When I left, I had the couch set to full brightness. You can turn the brightness down, but I'll make note of this and improve the power supply for the next run.
